# Generated by Django 4.0.6 on 2022-11-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeleneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(default='', max_length=256)),
                ('name', models.CharField(max_length=255)),
                ('main_tags', models.JSONField(default=list)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeleneModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=255)),
                ('is_current_version', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selene_models.selenemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SeleneNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_step', models.BooleanField(default=True)),
                ('do_after', models.JSONField(default=dict, null=True)),
                ('do_before', models.JSONField(default=dict, null=True)),
                ('end_steps', models.BooleanField(default=False)),
                ('tokenized_name', models.CharField(max_length=255)),
                ('next_node_on_option', models.JSONField(default=dict)),
                ('patterns', models.JSONField(default=list)),
                ('random_response', models.BooleanField(default=True)),
                ('responses', models.JSONField(default=list)),
                ('response_time_wait', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selene_models.selenemodelversion')),
                ('next_node', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_nodes', to='selene_models.selenenode')),
                ('next_node_version', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_selene_node_version', to='selene_models.selenenode')),
                ('previous_node', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_nodes', to='selene_models.selenenode')),
                ('previous_node_version', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_selene_node_version', to='selene_models.selenenode')),
            ],
        ),
        migrations.CreateModel(
            name='SeleneBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(default=None, null=True, upload_to='static/selene_chat_bots/')),
                ('cover_title', models.CharField(default='', max_length=30)),
                ('cover_description', models.CharField(default='', max_length=256)),
                ('default_response_on_webhook_failure', models.CharField(default='There was a problem with the request. Please try again later.', max_length=256)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selene_models.selenemodel')),
            ],
        ),
    ]
