# Generated by Django 4.0.6 on 2022-09-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selenemodel',
            name='model',
        ),
        migrations.AddField(
            model_name='selenemodel',
            name='model_path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
