# Generated by Django 4.0.6 on 2022-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selenemodel',
            name='model_path',
        ),
        migrations.RemoveField(
            model_name='selenenode',
            name='end_steps',
        ),
        migrations.AddField(
            model_name='selenemodelversion',
            name='version_model_path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
