# Generated by Django 4.0.6 on 2022-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0002_remove_selenemodel_model_selenemodel_model_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selenenode',
            name='responses_raw_text',
        ),
        migrations.AddField(
            model_name='selenenode',
            name='responses',
            field=models.JSONField(default=dict),
        ),
    ]
