# Generated by Django 4.0.6 on 2022-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0003_remove_selenenode_responses_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selenenode',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='selenenode',
            name='do_after',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='selenenode',
            name='do_before',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='selenenode',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
