# Generated by Django 4.0.6 on 2022-09-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0004_alter_selenenode_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selenenode',
            name='patterns_raw_text',
        ),
        migrations.AddField(
            model_name='selenemodel',
            name='main_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='selenenode',
            name='patterns',
            field=models.JSONField(default=list),
        ),
    ]
