# Generated by Django 4.0.6 on 2022-09-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0005_remove_selenenode_patterns_raw_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selenemodel',
            name='data_trained_with',
        ),
    ]
