# Generated by Django 4.0.6 on 2022-09-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0006_remove_selenemodel_data_trained_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selenemodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
