# Generated by Django 4.0.6 on 2022-09-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0007_alter_selenemodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selenemodel',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
