# Generated by Django 4.0.6 on 2022-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0008_alter_selenemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selenenode',
            name='patterns',
            field=models.JSONField(default=dict),
        ),
    ]
