# Generated by Django 4.0.6 on 2022-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0010_alter_selenenode_patterns_alter_selenenode_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='selenenode',
            name='response_time_wait',
            field=models.IntegerField(default=0),
        ),
    ]
