# Generated by Django 4.0.6 on 2022-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0011_selenenode_response_time_wait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selenenode',
            name='next_id',
        ),
        migrations.RemoveField(
            model_name='selenenode',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='selenenode',
            name='next_node_on_option',
            field=models.JSONField(default=dict),
        ),
    ]
