# Generated by Django 4.0.6 on 2022-09-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0012_remove_selenenode_next_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selenenode',
            name='end_steps',
            field=models.BooleanField(default=False),
        ),
    ]
