# Generated by Django 4.0.6 on 2022-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0013_selenenode_end_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='selenebot',
            name='cover_description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='selenebot',
            name='cover_image',
            field=models.ImageField(default=None, null=True, upload_to='static/selene_chat_bots/'),
        ),
        migrations.AddField(
            model_name='selenebot',
            name='cover_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
