# Generated by Django 4.0.6 on 2022-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0014_selenebot_cover_description_selenebot_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selenebot',
            name='default_response_on_webhook_failure',
            field=models.CharField(default='There was a problem with the request. Please try again later.', max_length=256),
        ),
        migrations.AddField(
            model_name='selenemodel',
            name='token',
            field=models.CharField(default='fDAhBUPugbcve6nozOYb1A', max_length=255),
        ),
    ]
