# Generated by Django 4.0.6 on 2022-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0015_selenebot_default_response_on_webhook_failure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selenenode',
            old_name='name',
            new_name='tokenized_name',
        ),
        migrations.AddField(
            model_name='selenemodel',
            name='is_main_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='selenemodel',
            name='token',
            field=models.CharField(default='pNVhOp0Kjn9aZLyYZUAySg', max_length=255),
        ),
    ]
