# Generated by Django 4.0.6 on 2022-09-07 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selene_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('is_client_satified', models.BooleanField()),
                ('selene_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selene_models.selenebot')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField()),
                ('understood_within_context', models.BooleanField()),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.interaction')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selene_models.selenenode')),
            ],
        ),
    ]
