# Generated by Django 4.0.6 on 2022-11-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selene_models', '0002_remove_selenemodel_model_path_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesent',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selene_models.selenenode'),
        ),
    ]
