# Generated by Django 4.0.6 on 2022-09-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesent',
            name='message',
        ),
        migrations.AddField(
            model_name='messagesent',
            name='message_object',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='finished_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='is_client_satified',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
